Models/Learner.cs
namespace ThongTinSinhVien.Models
{
	public class Learner
	{
		public Learner()
		{
			Enrollments = new HashSet<Enrollment>();
		}
		public int LearnerID { get; set; }
		public string LastName { get; set; }
		public string FirstMidName { get; set; }
		public DateTime EnrollmentDate { get; set; }
		public int MajorID { get; set; }
		public virtual Major? Major { get; set; }
		public virtual ICollection<Enrollment> Enrollments { get; set; }
	}
}

Controllers/LearnerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThongTinSinhVien.Data;
using ThongTinSinhVien.Models;

namespace ThongTinSinhVien.Controllers
{
	public class LearnerController : Controller
	{
		private SchoolContext db;
		public LearnerController(SchoolContext context)
		{
			db = context;
		}
		public IActionResult Index()
		{
			var learners = db.Learners.Include(m => m.Major).ToList();
			return View(learners);
		}
        public IActionResult Create()
        {
            //dùng 1 trong 2 cách để tạo SelectList gửi về View qua ViewBag để
            //hiển thị danh sách chuyên ngành (Majors)
            var majors = new List<SelectListItem>(); //cách 1
            foreach (var item in db.Majors)
            {
                majors.Add(new SelectListItem
                {
                    Text = item.MajorName,

                    Value = item.MajorID.ToString()
                });

            }
            ViewBag.MajorID = majors;
            ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName"); //cách 2
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("FirstMidName,LastName,MajorID,EnrollmentDate")]
Learner learner)
        {
            if (ModelState.IsValid)
            {
                db.Learners.Add(learner);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            //lại dùng 1 trong 2 cách tạo SelectList gửi về View để hiển thị danh sách Majors
            ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName");
            return View();
        }
    }
}

Views/Learner/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}
@model Learner
<h1>Create</h1>
<div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="Learner" asp-action="Create" method="post" class="mt-3">
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="FirstMidName" class="form-control" placeholder="First Mid Name">
            </div>
            <span asp-validation-for="FirstMidName" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="LastName" class="form-control" placeholder="Last Name">
            </div>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="MajorID" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="MajorID" class="custom-select mr-sm-2"
                        asp-items="@ViewBag.MajorID"></select>
            </div>
            <span asp-validation-for="MajorID" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnrollmentDate" class="form-control">
            </div>
            <span asp-validation-for="EnrollmentDate" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>
    </form>
</div>

Views/Learner/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}
@model IEnumerable<Learner>
<h1>Learner List</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Mã</th>
            <th>Tên</th>
            <th>Họ</th>
            <th>Ngành</th>
            <th>Ngày Nhập Học</th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td>@s.LearnerID</td>
                <td>@s.FirstMidName</td>
                <td>@s.LastName</td>
                <td>@s.Major.MajorName</td>
                <td>@s.EnrollmentDate</td>
                <td><a asp-action="Edit">Edit</a>|<a asp-action="Delete">Delete</a></td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Create" class="btn btn-primary">Create New Student</a>